version: '3'
services:

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: postgres!secret
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./create_table.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 15s
      retries: 5


  postgrest:
    image: postgrest/postgrest
    ports:
      - "3333:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:postgres!secret@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user # In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
    networks:
      - default

  # Attention
  eth-storage:
    build: .
    environment: 
      POSTGRES_URI: postgres://app_user:postgres!secret@db:5432/app_db
      ETH_URL: https://rpc.libmev.com/0xffFff449F1A35Eb0fAcCA8D4659D8E15CF2f77Ba
      START_BLOCK: 18817442
      CONFIRMATIONS_BLOCK: 0
      PERIOD: 5
    networks:
      - default
    depends_on: 
      db:
        condition: service_healthy
